---
name: httpd-php

releases:
- name: httpd-php
  version: latest

stemcells:
- alias: default
  os: ubunty-trusty
  version: latest

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

instance_groups:
- name: httpd-php
  azs:
  - z1
  instances: 1
  jobs:
  - name: httpd
    release: httpd-php
    properties:
      httpd:
        http-port: ((httpd_http-port))
  - name: php
    release: httpd-php
  vm_type: default
  stemcell: default
  networks:
  - name: default
    type: dynamic
